 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/standups", type: :request do
  # Standup. As you add validations to Standup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Standup.create! valid_attributes
      get standups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      standup = Standup.create! valid_attributes
      get standup_url(standup)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_standup_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      standup = Standup.create! valid_attributes
      get edit_standup_url(standup)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Standup" do
        expect {
          post standups_url, params: { standup: valid_attributes }
        }.to change(Standup, :count).by(1)
      end

      it "redirects to the created standup" do
        post standups_url, params: { standup: valid_attributes }
        expect(response).to redirect_to(standup_url(Standup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Standup" do
        expect {
          post standups_url, params: { standup: invalid_attributes }
        }.to change(Standup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post standups_url, params: { standup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested standup" do
        standup = Standup.create! valid_attributes
        patch standup_url(standup), params: { standup: new_attributes }
        standup.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the standup" do
        standup = Standup.create! valid_attributes
        patch standup_url(standup), params: { standup: new_attributes }
        standup.reload
        expect(response).to redirect_to(standup_url(standup))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        standup = Standup.create! valid_attributes
        patch standup_url(standup), params: { standup: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested standup" do
      standup = Standup.create! valid_attributes
      expect {
        delete standup_url(standup)
      }.to change(Standup, :count).by(-1)
    end

    it "redirects to the standups list" do
      standup = Standup.create! valid_attributes
      delete standup_url(standup)
      expect(response).to redirect_to(standups_url)
    end
  end
end
